In [1]:
import numpy as np
import pandas as pd

In [4]:
string_data = pd.Series(['aardvrk', 'artichoke', np.nan, 'avocado'])

In [5]:
string_data

0      aardvrk
1    artichoke
2          NaN
3      avocado
dtype: object

In [6]:
string_data.isnull()

0    False
1    False
2     True
3    False
dtype: bool

In [8]:
string_data[0] = None

In [9]:
string_data.isnull()

0     True
1    False
2     True
3    False
dtype: bool

In [10]:
from numpy import nan as NA

In [11]:
data = pd.Series([1, NA, 3.5, NA, 7])

In [12]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

In [15]:
data[data.notnull()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [16]:
data = pd.DataFrame([[1., 6.5, 3., ], [1., NA, NA], [NA, NA, NA], [NA, 6.5, 3.]])

In [18]:
data

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [20]:
cleaned = data.dropna()

In [21]:
cleaned

0    1    2
0  1.0  6.5  3.0

In [22]:
data.dropna(how='all')

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [23]:
data[4] = NA

In [24]:
data

0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

In [25]:
data.dropna(how='all', axis=1)

0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [26]:
df = pd.DataFrame(np.random.randn(7, 3))

In [28]:
df.iloc[:4, 1] = NA

In [29]:
df.iloc[:2, 2] = NA

In [30]:
df

0         1         2
0 -1.530153       NaN       NaN
1 -0.826314       NaN       NaN
2 -0.779039       NaN -1.916490
3  1.282748       NaN  0.386995
4  1.139575  0.006790  0.144310
5 -0.008947 -0.433934  0.093004
6  0.901964 -0.949100 -0.292138

In [31]:
df.dropna()

0         1         2
4  1.139575  0.006790  0.144310
5 -0.008947 -0.433934  0.093004
6  0.901964 -0.949100 -0.292138

In [35]:
df.dropna(thresh=2)

0         1         2
2 -0.779039       NaN -1.916490
3  1.282748       NaN  0.386995
4  1.139575  0.006790  0.144310
5 -0.008947 -0.433934  0.093004
6  0.901964 -0.949100 -0.292138

In [36]:
df.fillna(0)

0         1         2
0 -1.530153  0.000000  0.000000
1 -0.826314  0.000000  0.000000
2 -0.779039  0.000000 -1.916490
3  1.282748  0.000000  0.386995
4  1.139575  0.006790  0.144310
5 -0.008947 -0.433934  0.093004
6  0.901964 -0.949100 -0.292138

In [37]:
df.fillna({1: 0.5, 2: 0})

0         1         2
0 -1.530153  0.500000  0.000000
1 -0.826314  0.500000  0.000000
2 -0.779039  0.500000 -1.916490
3  1.282748  0.500000  0.386995
4  1.139575  0.006790  0.144310
5 -0.008947 -0.433934  0.093004
6  0.901964 -0.949100 -0.292138

In [38]:
_ = df.fillna(0, inplace=True)

In [40]:
df

0         1         2
0 -1.530153  0.000000  0.000000
1 -0.826314  0.000000  0.000000
2 -0.779039  0.000000 -1.916490
3  1.282748  0.000000  0.386995
4  1.139575  0.006790  0.144310
5 -0.008947 -0.433934  0.093004
6  0.901964 -0.949100 -0.292138

In [41]:
df = pd.DataFrame(np.random.randn(6, 3))

In [42]:
df.iloc[2:, 1] = NA

In [43]:
df.iloc[4:, 2] = NA

In [44]:
df

0         1         2
0  2.784897 -0.125529 -0.958879
1  0.487428  0.547516 -1.261006
2  0.760217       NaN  0.609530
3  0.537814       NaN  0.955727
4 -1.239710       NaN       NaN
5 -0.711497       NaN       NaN

In [45]:
df.fillna(method='ffill')

0         1         2
0  2.784897 -0.125529 -0.958879
1  0.487428  0.547516 -1.261006
2  0.760217  0.547516  0.609530
3  0.537814  0.547516  0.955727
4 -1.239710  0.547516  0.955727
5 -0.711497  0.547516  0.955727

In [46]:
df.fillna(method='ffill', limit =2)

0         1         2
0  2.784897 -0.125529 -0.958879
1  0.487428  0.547516 -1.261006
2  0.760217  0.547516  0.609530
3  0.537814  0.547516  0.955727
4 -1.239710       NaN  0.955727
5 -0.711497       NaN  0.955727

In [47]:
data = pd.Series([1., NA, 3.5, NA, 7])

In [48]:
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

In [50]:
data = pd.DataFrame({'k1': ['one', 'two'] * 3+ ['two'], 'k2': [1, 1, 2, 3, 3, 4, 4]})

In [51]:
data

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

In [52]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

In [54]:
data.drop_duplicates()

k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [56]:
data['v1'] = range(7)

In [57]:
data

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

In [58]:
data.drop_duplicates(['k1'])

k1  k2  v1
0  one   1   0
1  two   1   1

In [61]:
data.drop_duplicates(['k1', 'k2'])

k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5

In [2]:
data = pd.DataFrame({'food':['bacon', 'pulled pork', 'bacon',
                             'Pastrami', 'corned beff', 'Bacon',
                             'pastrami', 'honey ham', 'nova lox'], 
                    'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})

In [3]:
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beff     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [4]:
meat_to_animal = {'bacon': 'pig', 
                 'pulled pork': 'pig', 
                 'pastrami': 'cow', 
                 'corned beff': 'cow', 
                 'honey ham': 'pig', 
                 'nova lox': 'salmon'}

In [5]:
lowercased = data['food'].str.lower()

In [7]:
lowercased

0          bacon
1    pulled pork
2          bacon
3       pastrami
4    corned beff
5          bacon
6       pastrami
7      honey ham
8       nova lox
Name: food, dtype: object

In [9]:
data['animal'] = lowercased.map(meat_to_animal)

In [10]:
data

food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     Pastrami     6.0     cow
4  corned beff     7.5     cow
5        Bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [11]:
data['food'].map(lambda x: meat_to_animal[x.lower()])

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

In [12]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])

In [13]:
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [14]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [16]:
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [17]:
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [19]:
data = pd.DataFrame(np.arange(12).reshape(3, 4), index=['Ohio', 'Colorado', 'New York'],
                    columns=['one', 'two', 'three', 'four']) 

In [20]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [24]:
transform = lambda x: x[:4].upper()

In [27]:
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [28]:
data.index = data.index.map(transform)

In [29]:
data

one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [30]:
data.rename(index=str.title, columns=str.upper)

ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [31]:
data.rename(index={'OHIO': 'INDIANA'}, inplace=True)

In [32]:
data

one  two  three  four
INDIANA    0    1      2     3
COLO       4    5      6     7
NEW        8    9     10    11

In [33]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]

In [34]:
bins = [18, 25, 35, 60, 100]

In [35]:
cats = pd.cut(ages, bins)

In [36]:
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [38]:
cats.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [39]:
cats.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]],
              closed='right',
              dtype='interval[int64]')

In [40]:
pd.value_counts(cats)

(18, 25]     5
(35, 60]     3
(25, 35]     3
(60, 100]    1
dtype: int64

In [41]:
pd.cut(ages, [18, 26, 36, 61, 100], right=False)

[[18, 26), [18, 26), [18, 26), [26, 36), [18, 26), ..., [26, 36), [61, 100), [36, 61), [36, 61), [26, 36)]
Length: 12
Categories (4, interval[int64]): [[18, 26) < [26, 36) < [36, 61) < [61, 100)]

In [42]:
group_names = ['Youth', 'YoungAdult', 'MiddleAged', 'Senior']

In [43]:
pd.cut(ages, bins, labels=group_names)

[Youth, Youth, Youth, YoungAdult, Youth, ..., YoungAdult, Senior, MiddleAged, MiddleAged, YoungAdult]
Length: 12
Categories (4, object): [Youth < YoungAdult < MiddleAged < Senior]

In [44]:
data = np.random.rand(20)

In [45]:
pd.cut(data, 4, precision=2)

[(0.25, 0.49], (0.25, 0.49], (0.74, 0.98], (0.49, 0.74], (0.00015, 0.25], ..., (0.00015, 0.25], (0.49, 0.74], (0.49, 0.74], (0.25, 0.49], (0.49, 0.74]]
Length: 20
Categories (4, interval[float64]): [(0.00015, 0.25] < (0.25, 0.49] < (0.49, 0.74] < (0.74, 0.98]]

In [47]:
data = np.random.randn(1000)

In [48]:
cats = pd.qcut(data, 4)

In [49]:
cats

[(-3.393, -0.718], (-3.393, -0.718], (0.00337, 0.661], (-0.718, 0.00337], (-0.718, 0.00337], ..., (0.661, 3.678], (0.661, 3.678], (0.661, 3.678], (0.00337, 0.661], (0.00337, 0.661]]
Length: 1000
Categories (4, interval[float64]): [(-3.393, -0.718] < (-0.718, 0.00337] < (0.00337, 0.661] < (0.661, 3.678]]

In [50]:
pd.value_counts(cats)

(0.661, 3.678]       250
(0.00337, 0.661]     250
(-0.718, 0.00337]    250
(-3.393, -0.718]     250
dtype: int64

In [52]:
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1])

[(-1.354, 0.00337], (-1.354, 0.00337], (0.00337, 1.27], (-1.354, 0.00337], (-1.354, 0.00337], ..., (0.00337, 1.27], (0.00337, 1.27], (1.27, 3.678], (0.00337, 1.27], (0.00337, 1.27]]
Length: 1000
Categories (4, interval[float64]): [(-3.393, -1.354] < (-1.354, 0.00337] < (0.00337, 1.27] < (1.27, 3.678]]

In [54]:
data = pd.DataFrame(np.random.randn(1000, 4))

In [56]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.004145    -0.043788     0.002995    -0.000681
std       1.030257     1.008064     0.966823     1.010036
min      -3.427197    -3.450797    -3.066942    -2.919395
25%      -0.650150    -0.715787    -0.629715    -0.667366
50%       0.019115    -0.069785     0.019300    -0.033912
75%       0.702658     0.662389     0.602878     0.671200
max       3.434961     2.820576     4.013612     2.700090

In [57]:
col = data[2]

In [60]:
col[np.abs(col) > 3]

84     3.620690
186    3.231722
384   -3.002288
804    3.147226
807   -3.066942
865    4.013612
Name: 2, dtype: float64

In [66]:
data[(np.abs(data) > 3).any(1)]

0         1         2         3
84   1.764382 -1.399236  3.620690  1.034242
186 -0.809113  1.596090  3.231722  1.697724
203  3.434961  1.390929  0.540797  0.045552
308  1.060694 -3.450797  0.424784 -2.548200
316 -3.347302 -0.859460 -0.809516 -0.309972
384  0.569313  0.065699 -3.002288  0.123038
457 -3.427197 -0.491427  0.260389 -2.073989
504  3.050170  0.682680  1.242365 -1.154162
598 -0.215965 -3.045498 -0.283408 -0.863474
803 -3.361611  0.015539 -1.113000  0.334998
804  1.288789  0.122181  3.147226  0.519451
807  0.142121  0.807697 -3.066942  1.229721
844 -0.754882 -3.045573  0.013631  0.333216
865  1.427428 -1.410031  4.013612  0.045169

In [67]:
data[np.abs(data) > 3] = np.sign(data) * 3

In [68]:
data.describe()

0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean      0.004796    -0.043246     0.001051    -0.000681
std       1.025212     1.006369     0.959559     1.010036
min      -3.000000    -3.000000    -3.000000    -2.919395
25%      -0.650150    -0.715787    -0.629715    -0.667366
50%       0.019115    -0.069785     0.019300    -0.033912
75%       0.702658     0.662389     0.602878     0.671200
max       3.000000     2.820576     3.000000     2.700090

In [69]:
df = pd.DataFrame(np.arange(5 * 4).reshape((5, 4)))

In [71]:
sampler = np.random.permutation(5)

In [72]:
sampler

array([4, 3, 1, 0, 2])

In [73]:
df.take(sampler)

0   1   2   3
4  16  17  18  19
3  12  13  14  15
1   4   5   6   7
0   0   1   2   3
2   8   9  10  11

In [75]:
df.sample(n=5)

0   1   2   3
0   0   1   2   3
4  16  17  18  19
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [76]:
choice = pd.Series([5, 7, -1, 6, 4])

In [79]:
draws = choice.sample(n=10, replace=True)

In [80]:
draws

1    7
0    5
3    6
2   -1
2   -1
3    6
0    5
3    6
3    6
2   -1
dtype: int64

In [81]:
df = pd.DataFrame({'key':['b', 'b', 'a', 'c', 'a', 'b'], 'data1': range(6)})

In [82]:
df

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [84]:
pd.get_dummies(df['key'])

a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

In [92]:
dummies = pd.get_dummies(df['key'], prefix='key')

In [93]:
df_with_dummies = df[['data1']].join(dummies)

In [94]:
df_with_dummies

data1  key_a  key_b  key_c
0      0      0      1      0
1      1      0      1      0
2      2      1      0      0
3      3      0      0      1
4      4      1      0      0
5      5      0      1      0

In [95]:
mnames = ['movie_id', 'title', 'genres']

In [104]:
movies = pd.read_table('pydata-book-2nd-edition/datasets/movielens/movies.dat', sep='::',  header=None, names=mnames)

d:\Tools\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: read_table is deprecated, use read_csv instead.
  """Entry point for launching an IPython kernel.
d:\Tools\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.


In [105]:
movies[:10]

movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

In [109]:
all_genres = []

In [110]:
for x in movies.genres:
    all_genres.extend(x.split('|'))

In [114]:
genres = pd.unique(all_genres)

In [115]:
genres

array(['Animation', "Children's", 'Comedy', 'Adventure', 'Fantasy',
       'Romance', 'Drama', 'Action', 'Crime', 'Thriller', 'Horror',
       'Sci-Fi', 'Documentary', 'War', 'Musical', 'Mystery', 'Film-Noir',
       'Western'], dtype=object)

In [116]:
zero_matrix = np.zeros((len(movies), len(genres)))

In [119]:
dummies = pd.DataFrame(zero_matrix, columns=genres)

In [123]:
gen = movies.genres[0]

In [124]:
dummies.columns.get_indexer(gen.split('|'))

array([0, 1, 2], dtype=int64)

In [125]:
gen.split('|')

['Animation', "Children's", 'Comedy']

In [126]:
for i, gen in enumerate(movies.genres):
    indices = dummies.columns.get_indexer(gen.split('|'))
    dummies.iloc[i, indices] = 1

In [127]:
movies_windic = movies.join(dummies.add_prefix('Gennre_'))

In [130]:
movies_windic.iloc[0]

movie_id                                        1
title                            Toy Story (1995)
genres                Animation|Children's|Comedy
Gennre_Animation                                1
Gennre_Children's                               1
Gennre_Comedy                                   1
Gennre_Adventure                                0
Gennre_Fantasy                                  0
Gennre_Romance                                  0
Gennre_Drama                                    0
Gennre_Action                                   0
Gennre_Crime                                    0
Gennre_Thriller                                 0
Gennre_Horror                                   0
Gennre_Sci-Fi                                   0
Gennre_Documentary                              0
Gennre_War                                      0
Gennre_Musical                                  0
Gennre_Mystery                                  0
Gennre_Film-Noir                                0


In [131]:
np.random.seed(12345)

In [133]:
values = np.random.rand(10)

In [134]:
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [135]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]

In [136]:
pd.get_dummies(pd.cut(values,bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0           0           0           0           0           1
1           0           1           0           0           0
2           1           0           0           0           0
3           0           1           0           0           0
4           0           0           1           0           0
5           0           0           1           0           0
6           0           0           0           0           1
7           0           0           0           1           0
8           0           0           0           1           0
9           0           0           0           1           0

In [144]:
val = 'a,b,   guido'

In [145]:
val.split(',')

['a', 'b', '   guido']

In [146]:
pieces = [x.strip() for x in val.split(',')]

In [147]:
pieces

['a', 'b', 'guido']

In [148]:
first, second, third = pieces

In [149]:
first + '::' + second + '::' + third

'a::b::guido'

In [150]:
'::'.join(pieces)

'a::b::guido'

In [151]:
import re

In [152]:
text = "foo     bar\t baz   \tqux"

In [153]:
re.split('\s+', text)

['foo', 'bar', 'baz', 'qux']

In [156]:
regex = re.compile('\s+')

In [158]:
regex.split(text)

['foo', 'bar', 'baz', 'qux']